// DeVora — public API surface.

export * from "./types.ts"
export { VadDetector, DEFAULT_VAD_CONFIG } from "./vad/detector.ts"
export type { VadConfig, VadEvent } from "./vad/detector.ts"
export { TurnDetector } from "./conversation/turn.ts"
export type { TurnEvent } from "./conversation/turn.ts"
export { InterruptionCoordinator } from "./conversation/interruption.ts"
export type { InterruptionDeps, InterruptionResult } from "./conversation/interruption.ts"
export { VoiceController } from "./conversation/controller.ts"
export type { VoiceControllerOptions, ConversationMessage } from "./conversation/controller.ts"
export { Narrator } from "./narration/narrator.ts"
export type { NarrationSink } from "./narration/narrator.ts"
export { classifyNarration, priorityRank, PRIORITY_ORDER } from "./narration/filter.ts"
export type { OpencodeEventLike } from "./narration/filter.ts"
export { SdkBridge, TuiBridge } from "./opencode/bridge.ts"
export type { OpencodeBridge, BridgeEvent, BridgeEventHandler } from "./opencode/bridge.ts"
export { MockRecognizer } from "./stt/mock.ts"
export { VoskRecognizer } from "./stt/vosk.ts"
export { WhisperRecognizer } from "./stt/whisper.ts"
export type { SpeechRecognizer } from "./stt/client.ts"
export { MockSynthesizer } from "./tts/mock.ts"
export { PiperSynthesizer } from "./tts/piper.ts"
export type { SpeechSynthesizer } from "./tts/client.ts"
export { createAudioCapture } from "./audio/capture.ts"
export type { AudioCapture, CaptureEvents } from "./audio/capture.ts"
export { createRawPcmPlayback, playWaveFile } from "./audio/playback.ts"
export type { PlaybackSink } from "./audio/playback.ts"
export { listAudioDevices, defaultAudioDevice, isAudioAvailable } from "./audio/device.ts"
